### ISSUE TITLE
check_syntax, Component "function_" not found in structure

### ISSUE THREAD

**Issue by Zeatynis** [abaplint/transpiler#1154]
```
Error: check_syntax, Component "function_" not found in structure, ...clas.abap:104
check_syntax, Component "function_" not found in structure, ....clas.abap:145
check_syntax, Component "function_" not found in structure, ...clas.abap:153
check_syntax, Component "function_" not found in structure, ...clas.testclasses.abap:30
check_syntax, Component "function_" not found in structure, ...clas.testclasses.abap:54
check_syntax, Component "function_" not found in structure, ...clas.testclasses.abap:56
    at Transpiler.validate (...\node_modules\@abaplint\transpiler-cli\build\bundle.js:70177:19)     
    at Transpiler.run (...\node_modules\@abaplint\transpiler-cli\build\bundle.js:70125:14)
    at run (...\node_modules\@abaplint\transpiler-cli\build\bundle.js:90909:28)
    at ...\node_modules\@abaplint\transpiler-cli\build\bundle.js:90929:1
    at ...\node_modules\@abaplint\transpiler-cli\build\bundle.js:90936:3
    at Object.<anonymous> (...\node_modules\@abaplint\transpiler-cli\build\bundle.js:90938:12)      
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

![obraz](https://user-images.githubusercontent.com/9119187/226617722-7ed35aea-2919-4821-aa7b-c783e6434059.png)
```
REPORT zfoobar.

CLASS lcl_class DEFINITION.
  PUBLIC SECTION.

    TYPES: BEGIN OF ty_separator,
      function TYPE string,
      value TYPE string,
      END OF ty_separator.

    TYPES:  BEGIN OF ty_functions,
      separator TYPE ty_separator,
      END OF ty_functions.
    DATA functions TYPE ty_functions.
ENDCLASS.

CLASS lcl_class IMPLEMENTATION.
ENDCLASS.

DATA separator TYPE lcl_class=>ty_separator.
DATA mapper TYPE REF TO lcl_class.

separator-function = mapper->functions-separator.
```

```

class lcl_class {
  static INTERNAL_TYPE = 'CLAS';
  static IMPLEMENTED_INTERFACES = [];
  async constructor_(INPUT) {
    this.me = new abap.types.ABAPObject();
    this.me.set(this);
    this.functions = new abap.types.Structure({"separator": new abap.types.Structure({"function_": new abap.types.String({qualifiedName: "LCL_CLASS=>TY_SEPARATOR-FUNCTION_"}), "value": new abap.types.String({qualifiedName: "LCL_CLASS=>TY_SEPARATOR-VALUE"})}, "lcl_class=>ty_separator")}, "lcl_class=>ty_functions");
    return this;
  }
}
abap.Classes['PROG-ZFOOBAR-LCL_CLASS'] = lcl_class;
lcl_class.ty_separator = new abap.types.Structure({"function_": new abap.types.String({qualifiedName: "LCL_CLASS=>TY_SEPARATOR-FUNCTION_"}), "value": new abap.types.String({qualifiedName: "LCL_CLASS=>TY_SEPARATOR-VALUE"})}, "lcl_class=>ty_separator");
lcl_class.ty_functions = new abap.types.Structure({"separator": new abap.types.Structure({"function_": new abap.types.String({qualifiedName: "LCL_CLASS=>TY_SEPARATOR-FUNCTION_"}), "value": new abap.types.String({qualifiedName: "LCL_CLASS=>TY_SEPARATOR-VALUE"})}, "lcl_class=>ty_separator")}, "lcl_class=>ty_functions");
let separator = new abap.types.Structure({"function_": new abap.types.String({qualifiedName: "LCL_CLASS=>TY_SEPARATOR-FUNCTION_"}), "value": new abap.types.String({qualifiedName: "LCL_CLASS=>TY_SEPARATOR-VALUE"})}, "lcl_class=>ty_separator");
let mapper = new abap.types.ABAPObject({qualifiedName: "LCL_CLASS"});
separator.get().function_.set(mapper.get().functions.get().separator);
```

**Comment by Zeatynis** [comment]
I thought it is obvious but I will write it just to clarify.
It works if I replaced _function_ name with something different.
