### ISSUE TITLE
Error: Cannot find module 'util/types'

### ISSUE THREAD

**Issue by wwsheng009** [abaplint/transpiler#1307]
https://github.com/abaplint/transpiler/blob/ea6cffb1b029ed8d1361667af279f4b40de4d9c4/packages/runtime/src/statements/index.ts#L53C16-L53C16

when run the command npm run start-local in project open-table-maintenance, the build error occurs。Error detail as below:

Error: Cannot find module 'util/types'
Require stack:
- /home/vue/projects/open-table-maintenance/node_modules/@abaplint/runtime/build/src/statements/index.js
- /home/vue/projects/open-table-maintenance/node_modules/@abaplint/runtime/build/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/vue/projects/open-table-maintenance/node_modules/@abaplint/runtime/build/src/statements/index.js:51:17)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/vue/projects/open-table-maintenance/node_modules/@abaplint/runtime/build/src/statements/index.js',
    '/home/vue/projects/open-table-maintenance/node_modules/@abaplint/runtime/build/src/index.js'
  ]
}

**Comment by larshp** [comment]
are you testing https://github.com/open-abap/open-table-maintenance ?

**Comment by wwsheng009** [comment]
yes.

**Comment by larshp** [comment]
try again, https://github.com/open-abap/open-table-maintenance was updated earlier

**Comment by wwsheng009** [comment]
still not working ,it seems the function isAsyncFunction is missing in the below file.

https://github.com/abaplint/transpiler/tree/main/packages/runtime/src/statements/index.ts

**Comment by larshp** [comment]
how can the error be re-produced? and what is the error? is the error from https://github.com/abaplint/transpiler/issues/1307#issue-1868848321 gone?

**Comment by wwsheng009** [comment]
Node version v14 is not compatible with the abaplint runtime. replace the node with new version v16.19.1, the error has gone now.
