### ISSUE TITLE
`append lines of method_returning_itab(  ) to itab2` throws `TypeError: value.get is not a function` (after downport)

### ISSUE THREAD

**Issue by s7oev** [abaplint/transpiler#680]
As I do not get abaplint output with errors, but instead see the JS output with the `TypeError` directly, I assume there is a problem with the transpiler?

Reduced beer song example that gets executed without exceptions within an SAP system, but returns `TypeError` in exercism:

```abap
class zcl_beer_song definition public.
  public section.
    methods:
      recite
        importing initial_bottles_count type i
                  take_down_count       type i
        returning value(result)         type string_table.

  private section.
    methods:
      create_verse
        importing bottle        type i
        returning value(result) type string_table.
endclass.


class zcl_beer_song implementation.
  method recite.
    append lines of create_verse( 1 ) to result.
  endmethod.


  method create_verse.
    result = value #( ( `` ) ).
  endmethod.
endclass.
```

Full output:
```
TypeError: value.get is not a function
    at String.set (/usr/local/lib/node_modules/@abaplint/runtime/build/src/types/string.js:26:32)
    at Table.getValue (/usr/local/lib/node_modules/@abaplint/runtime/build/src/types/table.js:136:17)
    at Table.append (/usr/local/lib/node_modules/@abaplint/runtime/build/src/types/table.js:104:30)
    at Statements.append (/usr/local/lib/node_modules/@abaplint/runtime/build/src/statements/append.js:25:34)
    at zcl_beer_song.recite (file:///tmp/exercism-abap-runner-q84ff4/compiled/zcl_beer_song.clas.mjs:16:21)
    at async ltcl_beer_song.first_generic_verse (file:///tmp/exercism-abap-runner-q84ff4/compiled/zcl_beer_song.clas.testclasses.mjs:31:67)
    at async Function.run (file:///tmp/exercism-abap-runner-q84ff4/compiled/kernel_unit_runner.clas.mjs:126:11)
    at async run (file:///tmp/exercism-abap-runner-q84ff4/compiled/index_open.mjs:41:17)
```

**Comment by larshp** [comment]
case problem

**Comment by larshp** [comment]
@s7oev try again

![image](https://user-images.githubusercontent.com/5888506/161027012-293c42ae-e6cf-4045-a68b-fe8602c9ebda.png)

**Comment by s7oev** [comment]
[Full solution](https://exercism.org/tracks/abap/exercises/beer-song/solutions/s7oev) was accepted, which included both this issue + https://github.com/abaplint/abaplint/issues/2472 so can confirm it's fixed
