### ISSUE TITLE
Failed to parse URL error on Node 18

### ISSUE THREAD

**Issue by flaiker** [abaplint/transpiler#739]
On Node 18.2.0 I get this error:

![image](https://user-images.githubusercontent.com/5270359/170502257-4bbae0f5-e428-4e5e-8314-f3fee8af8307.png)

```
 TypeError: Failed to parse URL from /home/fabian/Code/abapGit/node_modules/sql.js/dist/sql-wasm.wasm
    at new Request (node:internal/deps/undici/undici:4813:19)
    at Agent.fetch2 (node:internal/deps/undici/undici:5539:29)
    ... 4 lines matching cause stack trace ...
    at /home/fabian/Code/abapGit/node_modules/sql.js/dist/sql-wasm.js:166:507
    at new Promise (<anonymous>)
    at initSqlJs (/home/fabian/Code/abapGit/node_modules/sql.js/dist/sql-wasm.js:22:24)
    at SQLiteDatabaseClient.connect (/home/fabian/Code/abapGit/node_modules/@abaplint/database-sqlite/build/index.js:11:48) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:377:5)
      at URL.onParseError (node:internal/url:563:9)
      at new URL (node:internal/url:643:5)
      at new Request (node:internal/deps/undici/undici:4811:25)
      at Agent.fetch2 (node:internal/deps/undici/undici:5539:29)
      at Object.fetch (node:internal/deps/undici/undici:6370:20)
      at fetch (node:internal/bootstrap/pre_execution:196:25)
      at /home/fabian/Code/abapGit/node_modules/sql.js/dist/sql-wasm.js:166:273
      at /home/fabian/Code/abapGit/node_modules/sql.js/dist/sql-wasm.js:166:494
      at /home/fabian/Code/abapGit/node_modules/sql.js/dist/sql-wasm.js:166:507 {
    input: '/home/fabian/Code/abapGit/node_modules/sql.js/dist/sql-wasm.wasm',
    code: 'ERR_INVALID_URL'
  }
}
```
Works fine on Node 16.15.0

**Comment by larshp** [comment]
thanks 👍 

use node 16 for now, hope someone/somehow identifies the error somewhere

**Comment by larshp** [comment]
@fabianlupa reproduce or close?

**Comment by fabianlupa** [comment]
I no longer have access to the setup, we'll just close the issue.
